/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Principal;

import Controlador.LibreriaBDControlador;
import Controlador.LibreriaToolsControlador;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPasswordField;

/**
 * @author Ángel González Rincón
 * Date: 01-sep-2021
 */
public class accesoPrincipal extends javax.swing.JFrame {

    /**
     * Acceso principal, ventana de loggeo.
     */
    
    LibreriaBDControlador lbd = new LibreriaBDControlador();
    LibreriaToolsControlador ltc = new LibreriaToolsControlador();
    int clicks_u = 0;
    int clicks_p = 0;    
    private String Usuario = "";
    private String Password = "";
    List <Object> listaDatosUsuarios = new ArrayList<Object>();
    
    public accesoPrincipal() {
        initComponents();
        Pass_Text.setEchoChar((char)0);
        Pass_Text.setText("PASSWORD");
        labelNotificacionError.setText("");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        User_TextField = new javax.swing.JTextField();
        CheckBoxPassword = new javax.swing.JCheckBox();
        Pass_Text = new javax.swing.JPasswordField();
        labelNotificacionError = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Obras Públicas");
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(615, 589));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/usuario_icono.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 57, -1, 82));

        User_TextField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        User_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        User_TextField.setText("USER");
        User_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        User_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                User_TextFieldMouseClicked(evt);
            }
        });
        jPanel1.add(User_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 179, 175, 37));

        CheckBoxPassword.setBackground(new java.awt.Color(255, 255, 255));
        CheckBoxPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        CheckBoxPassword.setText("Mostrar contraseña");
        CheckBoxPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(CheckBoxPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 278, -1, -1));

        Pass_Text.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Pass_Text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Pass_Text.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        Pass_Text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pass_TextMouseClicked(evt);
            }
        });
        jPanel1.add(Pass_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 234, 175, 37));

        labelNotificacionError.setForeground(new java.awt.Color(204, 0, 0));
        labelNotificacionError.setText("texto alerta");
        jPanel1.add(labelNotificacionError, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 382, 336, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(143, 195, 131));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ENTRAR");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 140, 30);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 600, 430));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(143, 195, 131));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextField1.setEnabled(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 70));

        jTextField3.setEditable(false);
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 600, 40));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField2.setText(" Obras Públicas");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void User_TextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_TextFieldMouseClicked
        if(clicks_u == 0){
        User_TextField.setText("");
        } 
        clicks_u ++;
    }//GEN-LAST:event_User_TextFieldMouseClicked

    private void CheckBoxPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxPasswordActionPerformed
        if(CheckBoxPassword.isSelected()){
            Pass_Text.setEchoChar((char)0);
        }else{
            Pass_Text.setEchoChar('*');
        }
    }//GEN-LAST:event_CheckBoxPasswordActionPerformed

    private void Pass_TextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pass_TextMouseClicked
        if(clicks_p == 0){
        Pass_Text.setText("");
        Pass_Text.setEchoChar('*');
        } 
        clicks_p ++;
    }//GEN-LAST:event_Pass_TextMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        clicks_u = 0;
        clicks_p = 0;
        
        //Ya puedo hacer uso de la conexión



        int validaResp = 0;
        Usuario = User_TextField.getText();
        Password = Pass_Text.getText();

        lbd.openConnection();
        listaDatosUsuarios = lbd.obtenerDatosUsuario("tabla_usuario_sesion", Usuario, Password);
        System.out.println("listaDatosUsuarios tamaño obtenido: "+listaDatosUsuarios.size()+"\nbotonInicioSesionActionPerformed :"+listaDatosUsuarios);
        lbd.closeConnection();
        
        validaResp = listaDatosUsuarios.size();
        if(validaResp != 0){
                        ventanaPrincipal ventanaPrincipal = new ventanaPrincipal();
                        this.dispose();
                        ventanaPrincipal.show();
        }else{
                System.out.println("No existe el usuario.");
                labelNotificacionError.setText("No existe el usuario.\nVerifica tu usuario y contraseña.");
            }
        

    }//GEN-LAST:event_jLabel2MouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(accesoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(accesoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(accesoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(accesoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new accesoPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxPassword;
    private javax.swing.JPasswordField Pass_Text;
    private javax.swing.JTextField User_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel labelNotificacionError;
    // End of variables declaration//GEN-END:variables
}
