/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Beneficiarios;

import Controlador.ControladorBaseDeDatos;
import Controlador.ControladorUtilerias;
import Modelo.TablaBeneficiarios;
import Modelo.TablaFotosBeneficiarios;
import Vista.Principal.ventanaPrincipal;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Luis Caamal Ic
 */
public class actualizarFotosBeneficiarios extends javax.swing.JFrame {

    /**
     * Creates new form fotosBeneficiario
     */
    ControladorBaseDeDatos cbd = new ControladorBaseDeDatos();
    ControladorUtilerias cut = new ControladorUtilerias();
    TablaBeneficiarios tbf = new TablaBeneficiarios();
    TablaFotosBeneficiarios tfb = new TablaFotosBeneficiarios();
    String ageObra = "";
    public actualizarFotosBeneficiarios(String ageObra,int idBeneficiario) {
        initComponents();
        this.tbf.setId(idBeneficiario);
        this.ageObra = ageObra;
        System.out.println("El año es:"+ageObra+" La informacion de id beneficiario: "+tbf.getId());
        //Valido que el usuario tenga información
        cbd.openConnection();
        tfb = cbd.obtenerFotos(tbf);
        cbd.closeConnection();
//        tfb.setFoto_uno("");
//        tfb.setFoto_dos("");
//        tfb.setFoto_tres("");
//        tfb.setFoto_cuatro("");
//        tfb.setFoto_cinco("");
//        tfb.setId_beneficiario(tbf.getId());
        if(tfb.getId()>0){
            jProgressBar1.setValue(100);
            jProgressBar2.setValue(100);
            jProgressBar3.setValue(100);
            jProgressBar4.setValue(100);
            jProgressBar5.setValue(100);
        }
        else{
           JOptionPane.showMessageDialog(null, "No existe información de documentos para este usuario, vuelve a registrarlo o eliminalo.");
           ventanaPrincipal vp = new ventanaPrincipal();
            this.dispose();
            vp.show();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDescargar2 = new javax.swing.JButton();
        btnDescargar3 = new javax.swing.JButton();
        btnDescargar4 = new javax.swing.JButton();
        btnDescargar5 = new javax.swing.JButton();
        btnDescargar1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jProgressBar5 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        izquierda_Button = new javax.swing.JLabel();
        derecha_Botton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a.setEditable(false);
        a.setBackground(new java.awt.Color(143, 195, 131));
        a.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        a.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        a.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, 30));

        jTextField3.setEditable(false);
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 600, 40));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField4.setText("Fotos \"beneficiario\"");
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("fotos.jpg");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 57, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("fotos.jpg");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 123, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("fotos.jpg");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 193, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("fotos.jpg");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("fotos.jpg");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        btnDescargar2.setBackground(new java.awt.Color(255, 255, 255));
        btnDescargar2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnDescargar2.setText("Descargar");
        btnDescargar2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 6, 4, new java.awt.Color(0, 0, 0)));
        btnDescargar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDescargar2.setOpaque(false);
        btnDescargar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDescargar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 85, 21));

        btnDescargar3.setBackground(new java.awt.Color(255, 255, 255));
        btnDescargar3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnDescargar3.setText("Descargar");
        btnDescargar3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 6, 4, new java.awt.Color(0, 0, 0)));
        btnDescargar3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDescargar3.setOpaque(false);
        btnDescargar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargar3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDescargar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 85, 21));

        btnDescargar4.setBackground(new java.awt.Color(255, 255, 255));
        btnDescargar4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnDescargar4.setText("Descargar");
        btnDescargar4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 6, 4, new java.awt.Color(0, 0, 0)));
        btnDescargar4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDescargar4.setOpaque(false);
        btnDescargar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargar4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDescargar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 85, 21));

        btnDescargar5.setBackground(new java.awt.Color(255, 255, 255));
        btnDescargar5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnDescargar5.setText("Descargar");
        btnDescargar5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 6, 4, new java.awt.Color(0, 0, 0)));
        btnDescargar5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDescargar5.setOpaque(false);
        btnDescargar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargar5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDescargar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 85, 21));

        btnDescargar1.setBackground(new java.awt.Color(255, 255, 255));
        btnDescargar1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnDescargar1.setText("Descargar");
        btnDescargar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 6, 4, new java.awt.Color(0, 0, 0)));
        btnDescargar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDescargar1.setOpaque(false);
        btnDescargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDescargar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 85, 21));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 57, 226, 21));
        jPanel1.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 226, 21));
        jPanel1.add(jProgressBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 226, 21));
        jPanel1.add(jProgressBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 226, 21));
        jPanel1.add(jProgressBar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 226, 21));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Actualiza o Añadir un Archivo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("Actualiza o Añadir un Archivo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setText("Actualiza o Añadir un Archivo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setText("Actualiza o Añadir un Archivo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setText("Actualiza o Añadir un Archivo");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 600, 440));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 0, 4, new java.awt.Color(0, 0, 0)));

        izquierda_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/flecha_izquierda.png"))); // NOI18N
        izquierda_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                izquierda_ButtonMouseClicked(evt);
            }
        });

        derecha_Botton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/flecha_derecha.png"))); // NOI18N
        derecha_Botton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                derecha_BottonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(izquierda_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(derecha_Botton)
                .addContainerGap(530, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(izquierda_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(derecha_Botton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void izquierda_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izquierda_ButtonMouseClicked
        ventanaPrincipal vp = new ventanaPrincipal();
        this.dispose();
        vp.show();
    }//GEN-LAST:event_izquierda_ButtonMouseClicked

    private void derecha_BottonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_derecha_BottonMouseClicked

    }//GEN-LAST:event_derecha_BottonMouseClicked

    private void btnDescargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargar1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Únicamente escribe el nombre del recuadro después de seleccionar la carpeta.");
        int operacionExitosa = 0;
        cbd.openConnection();
        String ruta = cut.obtenerRuta(1);
        operacionExitosa = cbd.guardarFoto(ruta, 1, tfb);
        cbd.closeConnection();
        if(operacionExitosa == 1){
            JOptionPane.showMessageDialog(null, "El archivo fue guardado con éxito en la siguiente dirección: "+ruta);
        
        }
        else{
            JOptionPane.showMessageDialog(null, "El archivo no fue guardado con éxito");
        }
    }//GEN-LAST:event_btnDescargar1ActionPerformed

    private void btnDescargar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargar2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Únicamente escribe el nombre del recuadro después de seleccionar la carpeta.");
        int operacionExitosa = 0;
        cbd.openConnection();
        String ruta = cut.obtenerRuta(1);
        operacionExitosa = cbd.guardarFoto(ruta, 2, tfb);
        cbd.closeConnection();
        if(operacionExitosa == 1){
            JOptionPane.showMessageDialog(null, "El archivo fue guardado con éxito en la siguiente dirección: "+ruta);
        
        }
        else{
            JOptionPane.showMessageDialog(null, "El archivo no fue guardado con éxito");
        }
    }//GEN-LAST:event_btnDescargar2ActionPerformed

    private void btnDescargar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargar3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Únicamente escribe el nombre del recuadro después de seleccionar la carpeta.");
        int operacionExitosa = 0;
        cbd.openConnection();
        String ruta = cut.obtenerRuta(1);
        operacionExitosa = cbd.guardarFoto(ruta, 3, tfb);
        cbd.closeConnection();
        if(operacionExitosa == 1){
            JOptionPane.showMessageDialog(null, "El archivo fue guardado con éxito en la siguiente dirección: "+ruta);
        
        }
        else{
            JOptionPane.showMessageDialog(null, "El archivo no fue guardado con éxito");
        }
    }//GEN-LAST:event_btnDescargar3ActionPerformed

    private void btnDescargar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargar4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Únicamente escribe el nombre del recuadro después de seleccionar la carpeta.");
        int operacionExitosa = 0;
        cbd.openConnection();
        String ruta = cut.obtenerRuta(1);
        operacionExitosa = cbd.guardarFoto(ruta, 4, tfb);
        cbd.closeConnection();
        if(operacionExitosa == 1){
            JOptionPane.showMessageDialog(null, "El archivo fue guardado con éxito en la siguiente dirección: "+ruta);
        
        }
        else{
            JOptionPane.showMessageDialog(null, "El archivo no fue guardado con éxito");
        }
    }//GEN-LAST:event_btnDescargar4ActionPerformed

    private void btnDescargar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargar5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Únicamente escribe el nombre del recuadro después de seleccionar la carpeta.");
        int operacionExitosa = 0;
        cbd.openConnection();
        String ruta = cut.obtenerRuta(1);
        operacionExitosa = cbd.guardarFoto(ruta,5, tfb);
        cbd.closeConnection();
        if(operacionExitosa == 1){
            JOptionPane.showMessageDialog(null, "El archivo fue guardado con éxito en la siguiente dirección: "+ruta);
        
        }
        else{
            JOptionPane.showMessageDialog(null, "El archivo no fue guardado con éxito");
        }
    }//GEN-LAST:event_btnDescargar5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JButton btnDescargar1;
    private javax.swing.JButton btnDescargar2;
    private javax.swing.JButton btnDescargar3;
    private javax.swing.JButton btnDescargar4;
    private javax.swing.JButton btnDescargar5;
    private javax.swing.JLabel derecha_Botton;
    private javax.swing.JLabel izquierda_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
