/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Beneficiarios;

import Vista.SeccionesObras.beneficiariosObra;

/**
 *
 * @author Usuario
 */
public class fotosBeneficiario extends javax.swing.JFrame {

    /**
     * Creates new form fotosBeneficiario
     */
    public fotosBeneficiario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jProgressBar5 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        browse = new javax.swing.JLabel();
        eliminar1 = new javax.swing.JLabel();
        eliminar2 = new javax.swing.JLabel();
        eliminar3 = new javax.swing.JLabel();
        eliminar4 = new javax.swing.JLabel();
        eliminar5 = new javax.swing.JLabel();
        browse1 = new javax.swing.JLabel();
        browse2 = new javax.swing.JLabel();
        browse3 = new javax.swing.JLabel();
        browse4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        izquierda_Button = new javax.swing.JLabel();
        derecha_Botton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a.setEditable(false);
        a.setBackground(new java.awt.Color(143, 195, 131));
        a.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        a.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        a.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, 30));

        jTextField3.setEditable(false);
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 600, 40));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField4.setText("Fotos \"beneficiario\"");
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("fotos.jpg");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 57, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("fotos.jpg");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 123, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("fotos.jpg");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 193, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("fotos.jpg");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("fotos.jpg");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 57, 226, 21));
        jPanel1.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 226, 21));
        jPanel1.add(jProgressBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 226, 21));
        jPanel1.add(jProgressBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 226, 21));
        jPanel1.add(jProgressBar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 226, 21));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Upload a file:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("Upload a file:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setText("Upload a file:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setText("Upload a file:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setText("Upload a file:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        browse.setBackground(new java.awt.Color(143, 195, 131));
        browse.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        browse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        browse.setText("Browse...");
        browse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        browse.setOpaque(true);
        browse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                browseMouseClicked(evt);
            }
        });
        jPanel1.add(browse, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 90, -1));

        eliminar1.setBackground(new java.awt.Color(143, 195, 131));
        eliminar1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        eliminar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminar1.setText("Eliminar");
        eliminar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        eliminar1.setOpaque(true);
        eliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminar1MouseClicked(evt);
            }
        });
        jPanel1.add(eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 100, -1));

        eliminar2.setBackground(new java.awt.Color(143, 195, 131));
        eliminar2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        eliminar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminar2.setText("Eliminar");
        eliminar2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        eliminar2.setOpaque(true);
        eliminar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminar2MouseClicked(evt);
            }
        });
        jPanel1.add(eliminar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 100, -1));

        eliminar3.setBackground(new java.awt.Color(143, 195, 131));
        eliminar3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        eliminar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminar3.setText("Eliminar");
        eliminar3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        eliminar3.setOpaque(true);
        eliminar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminar3MouseClicked(evt);
            }
        });
        jPanel1.add(eliminar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 100, -1));

        eliminar4.setBackground(new java.awt.Color(143, 195, 131));
        eliminar4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        eliminar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminar4.setText("Eliminar");
        eliminar4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        eliminar4.setOpaque(true);
        eliminar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminar4MouseClicked(evt);
            }
        });
        jPanel1.add(eliminar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 100, -1));

        eliminar5.setBackground(new java.awt.Color(143, 195, 131));
        eliminar5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        eliminar5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminar5.setText("Eliminar");
        eliminar5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        eliminar5.setOpaque(true);
        eliminar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminar5MouseClicked(evt);
            }
        });
        jPanel1.add(eliminar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 100, -1));

        browse1.setBackground(new java.awt.Color(143, 195, 131));
        browse1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        browse1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        browse1.setText("Browse...");
        browse1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        browse1.setOpaque(true);
        browse1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                browse1MouseClicked(evt);
            }
        });
        jPanel1.add(browse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 90, -1));

        browse2.setBackground(new java.awt.Color(143, 195, 131));
        browse2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        browse2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        browse2.setText("Browse...");
        browse2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        browse2.setOpaque(true);
        browse2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                browse2MouseClicked(evt);
            }
        });
        jPanel1.add(browse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 90, -1));

        browse3.setBackground(new java.awt.Color(143, 195, 131));
        browse3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        browse3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        browse3.setText("Browse...");
        browse3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        browse3.setOpaque(true);
        browse3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                browse3MouseClicked(evt);
            }
        });
        jPanel1.add(browse3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 90, -1));

        browse4.setBackground(new java.awt.Color(143, 195, 131));
        browse4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        browse4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        browse4.setText("Browse...");
        browse4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        browse4.setOpaque(true);
        browse4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                browse4MouseClicked(evt);
            }
        });
        jPanel1.add(browse4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 600, 440));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 0, 4, new java.awt.Color(0, 0, 0)));

        izquierda_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/flecha_izquierda.png"))); // NOI18N
        izquierda_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                izquierda_ButtonMouseClicked(evt);
            }
        });

        derecha_Botton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/flecha_derecha.png"))); // NOI18N
        derecha_Botton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                derecha_BottonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(izquierda_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(derecha_Botton)
                .addContainerGap(526, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(izquierda_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(derecha_Botton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void izquierda_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izquierda_ButtonMouseClicked
        beneficiariosObra benOb = new beneficiariosObra();
        this.dispose();
        benOb.show();
    }//GEN-LAST:event_izquierda_ButtonMouseClicked

    private void derecha_BottonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_derecha_BottonMouseClicked

    }//GEN-LAST:event_derecha_BottonMouseClicked

    private void browseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browseMouseClicked

    }//GEN-LAST:event_browseMouseClicked

    private void eliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar1MouseClicked

    private void eliminar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar2MouseClicked

    private void eliminar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar3MouseClicked

    private void eliminar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar4MouseClicked

    private void eliminar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar5MouseClicked

    private void browse1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browse1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_browse1MouseClicked

    private void browse2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browse2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_browse2MouseClicked

    private void browse3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browse3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_browse3MouseClicked

    private void browse4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browse4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_browse4MouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(fotosBeneficiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(fotosBeneficiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(fotosBeneficiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(fotosBeneficiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new fotosBeneficiario().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JLabel browse;
    private javax.swing.JLabel browse1;
    private javax.swing.JLabel browse2;
    private javax.swing.JLabel browse3;
    private javax.swing.JLabel browse4;
    private javax.swing.JLabel derecha_Botton;
    private javax.swing.JLabel eliminar1;
    private javax.swing.JLabel eliminar2;
    private javax.swing.JLabel eliminar3;
    private javax.swing.JLabel eliminar4;
    private javax.swing.JLabel eliminar5;
    private javax.swing.JLabel izquierda_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
